project:
  type: website
  output-dir: docs

website:
  title: "BRFSS Mental Distress Project"
  site-url: "https://alfie0925.github.io/biostat620-final-project/"
  repo-url: "https://github.com/Alfie0925/biostat620-final-project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data-processing.qmd
        text: Data Processing
    right:
      - icon: github
        href: "https://github.com/Alfie0925/biostat620-final-project"
  page-footer:
    left: "BIOSTAT 620 Final Project"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: true
    code-summary: "Show code"
    fig-align: center
    number-sections: false
    smooth-scroll: true

editor: visual
